# Generated by Django 2.0.5 on 2018-05-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Selecciona el género de este libro', to='biblioteca.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Selecciona el idioma de este libro', to='biblioteca.Language'),
        ),
    ]
