# Generated by Django 2.0.5 on 2018-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20180529_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='sinopsis',
            field=models.CharField(blank=True, help_text='Introduce una sinopsis del género', max_length=200, null=True),
        ),
    ]
