# Generated by Django 2.0.5 on 2018-05-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='pub_date',
        ),
    ]
